name: Build & Release (Foundry Module)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (mit LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: LFS Pull
        run: git lfs pull

      - name: Version aus Tag
        id: vars
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: module.json patchen (version + download)
        run: |
          VER="${{ steps.vars.outputs.version }}"
          jq --arg v "$VER" \
             '.version=$v |
              .download="https://github.com/Chaaaaaaaaarlie/dicesoniceviking/releases/download/v"+$v+"/svik4s-"+$v+".zip"' \
             module.json > module.json.tmp && mv module.json.tmp module.json
          jq '.version, .download' module.json

      - name: ZIP bauen (Top-Level!)
        run: |
          VER="${{ steps.vars.outputs.version }}"
          zip -r "svik4s-$VER.zip" module.json SVIK4S.js blue green purple red turkis

      - name: Release + Asset
        uses: softprops/action-gh-release@v2
        with:
          files: svik4s-${{ steps.vars.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Manifest zurück auf main committen
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: actions@github.com
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          VER="${{ steps.vars.outputs.version }}"
          git checkout "$DEFAULT_BRANCH"
          git pull
          jq --arg v "$VER" \
             '.version=$v |
              .download="https://github.com/Chaaaaaaaaarlie/dicesoniceviking/releases/download/v"+$v+"/svik4s-"+$v+".zip"' \
             module.json > module.json.tmp && mv module.json.tmp module.json
          git add module.json
          git diff --cached --quiet || git commit -m "chore: bump module.json to $VER [skip ci]"
          git push
